version: '3'
services:
  python:
    build: .
    container_name: youtubechecker-app
    ports:
      - "5000:80"
    environment:
      TZ: Asia/Tokyo
      #FLASK_ENV: development
      FLASK_APP: myapp.py
    volumes:
      - ./app:/workspace/app